name: Build EXE
on: push     
jobs:
  build_dll:
          runs-on: windows-latest
          steps:
                  - name: Checkout
                    uses: actions/checkout@v2
                  - name: Setup MSBuild
                    uses: microsoft/setup-msbuild@v1
                  - name: Build EXE
                    run: 'msbuild PathOfBuilding-Launcher.vcxproj /p:configuration=release /p:platform=win32'
                  - name: Archive EXE
                    uses: actions/upload-artifact@v1.0.0
                    with:
                        name: Path of Building.exe
                        path: '${{ github.workspace }}/Release/Path of Building.exe'
