name: Build EXE
on: [push, workflow_dispatch]     
jobs:
  build_exe:
          runs-on: windows-latest
          steps:
                  - name: Checkout
                    uses: actions/checkout@v4
                  - name: Setup MSBuild
                    uses: microsoft/setup-msbuild@v1
                  - name: Build EXE
                    run: 'msbuild PathOfBuilding-Launcher.vcxproj /p:configuration=release /p:platform=x64'
                  - name: Archive EXE
                    uses: actions/upload-artifact@v3
                    with:
                        name: Path of Building.exe
                        path: '${{ github.workspace }}/x64/Release/Path of Building.exe'
